#pragma once

#define IOCTL_INTEGRITY_GET_EVENTS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_INTEGRITY_CLEAR_EVENTS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_INTEGRITY_GET_COUNT CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_INTEGRITY_GET_VERSION CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_INTEGRITY_ENUM_PROCESSES CTL_CODE(FILE_DEVICE_UNKNOWN, 0x804, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_INTEGRITY_HIDDEN_PROCESS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x805, METHOD_NEITHER, FILE_READ_ACCESS)
#define IOCTL_INTEGRITY_READ_MEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 0x806, METHOD_NEITHER, FILE_READ_ACCESS)

#define EVENT_PROCESS_CREATED    1
#define EVENT_PROCESS_TERMINATED 2
#define EVENT_THREAD_CREATED     3
#define EVENT_IMAGE_LOADED       4
#define EVENT_HANDLE_OPEN        5
#define EVENT_HIDDEN_PROCESS     6
#define EVENT_SUSPICIOUS         99

#pragma pack(push, 1)
typedef struct _INTEGRITY_EVENT {
    ULONG EventType;
    ULONGLONG Timestamp;
    ULONG ProcessId;
    WCHAR ProcessName[256];
    WCHAR ImagePath[260];
    ULONG TargetProcessId;
    ULONG HandleId;
    BOOLEAN IsSuspicious;
} INTEGRITY_EVENT;

typedef struct _PROCESS_ENTRY {
    ULONG ProcessId;
    ULONG ParentProcessId;
    ULONG SessionId;
    ULONG Flags;          // 0 = normal, 1 = hidden, 2 = protected
    ULONG ThreadCount;
    ULONG HandleCount;
    WCHAR ProcessName[256];
    WCHAR ImagePath[260];
    LONGLONG CreateTime;
    SIZE_T VirtualSize;
    SIZE_T WorkingSetSize;
} PROCESS_ENTRY;

typedef struct _HIDDEN_PROCESS_SCAN {
    ULONG FoundCount;
    ULONG HiddenCount;
    ULONG ProtectedCount;
    ULONG UnlinkedCount;
    ULONG_PTR SuspiciousEprocess[32];
} HIDDEN_PROCESS_SCAN;

typedef struct _MEMORY_READ_REQUEST {
    ULONG ProcessId;
    ULONGLONG Address;
    ULONG Size;
    UCHAR Buffer[4096];
} MEMORY_READ_REQUEST;
#pragma pack(pop)
